# This is the configuration used to check the rubocop source code.
require:
  - rubocop/cop/internal_affairs
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - "vendor/**/*"
    - "spec/fixtures/**/*"
    - "tmp/**/*"
    - ".git/**/*"
    - "bin/*"
    - "spec/test_data.rb"
  TargetRubyVersion: 3.0.2
  SuggestExtensions: false

Naming/PredicateName:
  # Method define macros for dynamically generated method.
  MethodDefinitionMacros:
    - define_method
    - define_singleton_method
    - def_node_matcher
    - def_node_search

Style/AccessorGrouping:
  Exclude:
    - lib/rubocop/formatter/base_formatter.rb
    - lib/rubocop/cop/offense.rb

Style/FormatStringToken:
  # Because we parse a lot of source codes from strings. Percent arrays
  # look like unannotated format string tokens to this cop.
  Exclude:
    - spec/**/*

Style/IpAddresses:
  # The test for this cop includes strings that would cause offenses
  Exclude:
    - spec/rubocop/cop/style/ip_addresses_spec.rb

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/ClassStructure:
  Enabled: true

Layout/RedundantLineBreak:
  Enabled: true

Layout/TrailingWhitespace:
  AllowInHeredoc: false

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*.rb"

Layout/HashAlignment:
  EnforcedHashRocketStyle:
    - key
    - table
  EnforcedColonStyle:
    - key
    - table

Layout/LineLength:
  Max: 120
  IgnoredPatterns:
    - !ruby/regexp /\A +(it|describe|context|shared_examples|include_examples|it_behaves_like) ["']/

Lint/InterpolationCheck:
  Exclude:
    - "spec/**/*.rb"

Metrics/MethodLength:
  Max: 30

Lint/UselessAccessModifier:
  MethodCreatingMethods:
    - "def_matcher"
    - "def_node_matcher"

Lint/BooleanSymbol:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "Rakefile"
    - "**/*.rake"
    - "spec/**/*.rb"
    - "**/*.gemspec"

Metrics/ClassLength:
  Exclude:
    - lib/rubocop/config_obsoletion.rb

Metrics/ModuleLength:
  Exclude:
    - "spec/**/*.rb"

Naming/VariableNumber:
  Exclude:
    - config/initializers/semantic_logger.rb

Naming/InclusiveLanguage:
  FlaggedTerms:
    offence:
      Suggestions:
        - offense
  Exclude:
    - lib/rubocop/cop/naming/inclusive_language.rb

RSpec/FilePath:
  Exclude:
    - spec/rubocop/cop/internal_affairs/redundant_let_rubocop_config_new_spec.rb
    - spec/rubocop/formatter/junit_formatter_spec.rb

RSpec/PredicateMatcher:
  Enabled: false

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/NestedGroups:
  Max: 7

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/StubbedMock:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

InternalAffairs/ExampleDescription:
  Include:
    - "spec/rubocop/cop/**/*.rb"

InternalAffairs/UndefinedConfig:
  Include:
    - "lib/rubocop/cop/**/*.rb"
  Exclude:
    - "lib/rubocop/cop/correctors/**/*.rb"
    - "lib/rubocop/cop/mixin/**/*.rb"

Style/Documentation:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false
